version: 0.2
phases:
  install:
    runtime-versions:
      java: openjdk11
  pre_build:
    commands:
    - echo In the pre_build phase...
  build:
    commands:
    - echo Build started on `date`
    - mvn  clean install -DskipTests
  post_build:
    commands:
    - echo Build completed on `date`
artifacts:
  files:
  - target/0.0.1-SNAPSHOT.jar
